# Generated by Django 4.0.6 on 2023-12-27 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('users', '0001_initial'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtactic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='teamtactic',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='teamnotification',
            name='links',
            field=models.ManyToManyField(blank=True, to='teams.notificationlink'),
        ),
        migrations.AddField(
            model_name='teamnotification',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='profileID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='teamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationmember'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(db_index=True, related_name='team_members', through='teams.TeamMember', to='users.profile'),
        ),
        migrations.AddField(
            model_name='tacticimage',
            name='team_tactic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactic_images', to='teams.teamtactic'),
        ),
        migrations.AddField(
            model_name='physicalassessmentscore',
            name='physical_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.physicalassessment'),
        ),
        migrations.AddField(
            model_name='physicalassessmentscore',
            name='physical_assessment_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.physicalassessmentrecord'),
        ),
        migrations.AddField(
            model_name='physicalassessmentscore',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='physicalassessmentscore',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teammember'),
        ),
        migrations.AddField(
            model_name='physicalassessmentrecord',
            name='physical_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.physicalassessment'),
        ),
        migrations.AddField(
            model_name='physicalassessmentrecord',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='physicalassessment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='notificationlink',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='event',
            name='email_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.teamnotification'),
        ),
        migrations.AddField(
            model_name='event',
            name='teamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='teams.team'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.event'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teammember'),
        ),
        migrations.AddField(
            model_name='athletemarkforevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.event'),
        ),
        migrations.AddField(
            model_name='athletemarkforevent',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teammember'),
        ),
        migrations.AddField(
            model_name='athleteinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='athleteinvitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('profileID', 'teamID')},
        ),
        migrations.AlterUniqueTogether(
            name='physicalassessmentscore',
            unique_together={('physical_assessment', 'physical_assessment_record', 'team_member', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='physicalassessmentrecord',
            unique_together={('physical_assessment', 'team', 'physical_assessment_date')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('team_member', 'event', 'team')},
        ),
    ]
