# Generated by Django 4.0.6 on 2024-01-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='athlete_gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Not Required')], db_index=True, default='3', max_length=2),
        ),
    ]
