# Generated by Django 4.0.6 on 2024-01-07 02:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationphysicalassessment'),
        ('teams', '0003_team_athlete_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPhysicalAssessmentRecord',
            fields=[
                ('physical_assessment_date', models.DateField(db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizations')),
                ('physical_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationphysicalassessment')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'unique_together': {('physical_assessment', 'team', 'physical_assessment_date', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationPhysicalAssessmentScore',
            fields=[
                ('score', models.FloatField(blank=True, db_index=True, null=True)),
                ('time', models.DurationField(blank=True, db_index=True, null=True)),
                ('distance', models.FloatField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizations')),
                ('physical_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationphysicalassessment')),
                ('physical_assessment_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.organizationphysicalassessmentrecord')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teammember')),
            ],
            options={
                'unique_together': {('physical_assessment', 'physical_assessment_record', 'team_member', 'team', 'organization')},
            },
        ),
    ]
