# Generated by Django 4.0.6 on 2024-01-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationphysicalassessment'),
        ('teams', '0004_organizationphysicalassessmentrecord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationphysicalassessmentrecord',
            old_name='physical_assessment',
            new_name='org_physical_assessment',
        ),
        migrations.RenameField(
            model_name='organizationphysicalassessmentrecord',
            old_name='physical_assessment_date',
            new_name='org_physical_assessment_date',
        ),
        migrations.RenameField(
            model_name='organizationphysicalassessmentscore',
            old_name='physical_assessment',
            new_name='org_physical_assessment',
        ),
        migrations.RenameField(
            model_name='organizationphysicalassessmentscore',
            old_name='physical_assessment_record',
            new_name='org_physical_assessment_record',
        ),
        migrations.AlterUniqueTogether(
            name='organizationphysicalassessmentrecord',
            unique_together={('org_physical_assessment', 'team', 'org_physical_assessment_date', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationphysicalassessmentscore',
            unique_together={('org_physical_assessment', 'org_physical_assessment_record', 'team_member', 'team', 'organization')},
        ),
    ]
