# Generated by Django 5.0.4 on 2024-04-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_rename_physical_assessment_organizationphysicalassessmentrecord_org_physical_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('1', 'Athlete'), ('2', 'Coach'), ('3', 'Staff'), ('4', 'Owner')], db_index=True, default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='team',
            name='athlete_gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Mixed'), ('4', 'Not Required')], db_index=True, default='3', max_length=2),
        ),
    ]
