# Generated by Django 4.0.6 on 2024-01-05 02:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPhysicalAssessment',
            fields=[
                ('opa_title', models.CharField(max_length=70)),
                ('assessment_type', models.CharField(choices=[('time', 'Time'), ('score', 'Score'), ('distance', 'Distance')], db_index=True, default='score', max_length=10)),
                ('best_score_lower', models.BooleanField(db_index=True, default=False)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizations')),
            ],
        ),
    ]
