# Generated by Django 5.0.4 on 2024-05-13 21:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='org_role',
            field=models.CharField(choices=[('1', 'Coach'), ('2', 'Coach/Manager'), ('3', 'Manager'), ('4', 'Owner'), ('5', 'Staff')], db_index=True, default='1', max_length=2),
        ),
        migrations.CreateModel(
            name='OrgSubscriptionPlan',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('org_member_limit', models.IntegerField()),
                ('team_limit_for_coach', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('team_member_limit', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('tactic_play_limit', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('tactic_count_limit', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organizations')),
            ],
        ),
    ]
