# Generated by Django 5.0.4 on 2024-05-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organizationmember_org_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizations',
            name='subscription_plan',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
